name: Build
on: [ "push" ]
jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: ['1.24.x']
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v5
      with:
        go-version: '${{ matrix.go-version }}'

    - name: Build
      run: go build -v ./...

    - name: Run tests
      run: go test -v ./...

    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository_owner }}/ws2wh
        tags: |
          type=semver,pattern={{version}}
          type=ref,event=branch
          type=sha,format=short

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}