on:
  schedule:
    - cron: "0 1 * * *"
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest release
        uses: octokit/request-action@v2.4.0
        id: get_latest_release
        with:
          route: GET /repos/{owner}/{repo}/releases/latest
      - run: "echo latest release: '${{ steps.get_latest_release.outputs.data }}'"

      - name: Aqua Security Trivy
        uses: aquasecurity/trivy-action@0.29.0
        with:
          image-ref: ghcr.io/ws2wh/ws2wh:${{ steps.get_latest_release.outputs.data.tag_name }}
          format: 'table'
          exit-code: '1'

